version: '3.8'

services:
  neo4j:
    image: neo4j:5.15
    container_name: neo4j-matrimony
    hostname: neo4j-matrimony
    ports:
      - "7474:7474"  # HTTP - Neo4j Browser
      - "7687:7687"  # Bolt - Database connection
    environment:
      # Authentication
      NEO4J_AUTH: neo4j/matrimony123456!
      
      # Database name
      NEO4J_PLUGINS: '["apoc", "apoc-extended"]'
      
      # APOC Configuration (Advanced Procedures)
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      NEO4J_dbms_security_procedures_whitelist: apoc.*
      NEO4J_apoc_export_file_enabled: true
      NEO4J_apoc_import_file_enabled: true
      NEO4J_apoc_import_file_use__neo4j__config: true
      
      # Memory Configuration (Optimized for matrimony platform)
      NEO4J_dbms_memory_heap_initial_size: 2G
      NEO4J_dbms_memory_heap_max_size: 4G
      NEO4J_dbms_memory_pagecache_size: 2G
      
      # Connection Configuration
      NEO4J_dbms_default_listen_address: 0.0.0.0
      NEO4J_dbms_connector_bolt_listen_address: 0.0.0.0:7687
      NEO4J_dbms_connector_http_listen_address: 0.0.0.0:7474
      
      # Performance Tuning for Family Graph Operations
      NEO4J_dbms_tx_log_rotation_retention_policy: "100M size"
      NEO4J_dbms_checkpoint_interval_time: 15m
      NEO4J_dbms_checkpoint_interval_tx: 100000
      
      # Query Performance
      NEO4J_dbms_query_cache_size: 1000
      NEO4J_dbms_query_plan_cache_size: 1000
      
      # Logging Configuration
      NEO4J_dbms_logs_query_enabled: true
      NEO4J_dbms_logs_query_threshold: 1s
      NEO4J_dbms_logs_query_parameter_logging_enabled: false
      
      # Security Settings
      NEO4J_dbms_security_auth_enabled: true
      NEO4J_dbms_security_auth_minimum_password_length: 8
      
      # Monitoring
      NEO4J_metrics_enabled: true
      NEO4J_metrics_prometheus_enabled: true
      NEO4J_metrics_prometheus_endpoint: 0.0.0.0:2004
      
      # Browser Configuration
      NEO4J_browser_remote_content_hostname_whitelist: "*"
      NEO4J_browser_credential_timeout: 0
      
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
      - neo4j-import:/var/lib/neo4j/import
      - neo4j-plugins:/plugins
      - neo4j-conf:/var/lib/neo4j/conf
      - ./backups:/backups
      
    networks:
      - matrimony-network
      
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u neo4j -p matrimony123456! 'RETURN 1' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
      
    deploy:
      resources:
        limits:
          memory: 6G
          cpus: '2.0'
        reservations:
          memory: 4G
          cpus: '1.0'
    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.neo4j.rule=Host(`neo4j.localhost`)"
      - "traefik.http.services.neo4j.loadbalancer.server.port=7474"

volumes:
  neo4j-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/neo4j
  neo4j-logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./logs/neo4j
  neo4j-import:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./import
  neo4j-plugins:
  neo4j-conf:

networks:
  matrimony-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16